name: Build Aseprite (Windows)
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    # 安装必要工具
    - name: Install prerequisites
      shell: powershell
      run: |
        choco install 7zip -y
        choco install ninja -y
    
    # 下载Skia
    - name: Download Skia
      shell: bash
      run: |
        SKIA_VERSION=m102-861e4743af
        curl -L "https://github.com/aseprite/skia/releases/download/${SKIA_VERSION}/Skia-Windows-Release-x64.zip" -o skia.zip
        7z x skia.zip -o skia -y
        ls skia/out/Release-x64 || echo "Skia extraction failed"
    
    # 设置MSVC环境
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    
    # 配置构建
    - name: Configure CMake
      shell: cmd
      run: |
        cmake -S . -B build -G Ninja ^
          -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
          -DLAF_BACKEND=skia ^
          -DENABLE_SCRIPTING=ON ^
          -DSKIA_DIR="%cd%\skia" ^
          -DSKIA_LIBRARY_DIR="%cd%\skia\out\Release-x64"
    
    # 编译
    - name: Build
      shell: cmd
      run: |
        cd build
        ninja
    
    # 打包结果
    - name: Package Artifacts
      shell: bash
      run: |
        mkdir -p package
        cp build/bin/aseprite.exe package/
        cp -r build/bin/data package/
        7z a aseprite.zip ./package/*
    
    # 上传制品
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Aseprite-Windows
        path: aseprite.zip
